### ISSUE TITLE
TO-DO Improvements

### ISSUE THREAD

**Issue by pedrofran12** [pedrofran12/hpim_dm#2]
This issue lists some ideas and future improvements that could be performed to HPIM-DM implementation/specification.

- [ ] Relax the interest storage requirement of Assert Losers. Requires updating the specification.
- [ ] BFD support?
- [x] Multiple physical interfaces of the same router directly connected to the source. If these interfaces are not a LAG there is the possibility of a loop (one interface considered root and the other(s) non-root -> which may cause data packets to be forwarded again to the source subnet by the non-root interface). Check specification and implementation if there is no issue (DONE #6).
- [x] Security -> Implement control message integrity & authentication check (DONE #3).
- [ ] IGMPv3 and MLDv2.
- [x] IPv6 multicast routing support (update Kernel and implement MLD). (DONE #7)
- [ ] Option to ignore the Feasibility Condition in determining the tree state. This may be useful in sub-topologies where it is impossible to form a network loop and in which there are different routing protocols being used (ex: all routers use OSPF but a subset uses default static routes).
- [x] All code should be in hpimdm package (in order to allow hpim-dm and pim-dm implementations to coexist). (DONE #4)
- [ ] More automation on tests.
- [x] Forwarding state of a non-root interface that was AW should be preserved for a given amount of time to prevent loss of data packets when the AW changes. (DONE #5)
- [ ] Better debug messages.
- [ ] Try to remove tcpdump dependency (manually create BPF filter bytecode).
- [ ] Change API used to access unicast routing information (ipdb will become deprecated).
- [x] Perform tests using other environment (current one does not have support for IPv6 multicast routing - limitations at the kernel level).
- [x] Multiple tables support. (DONE)
- [x] Have a configuration file to configure everything on startup.(DONE)
- [ ] Multicast routing protocol takes into consideration interest of own router (router has application that joined some multicast groups)
